logging:
  level: INFO
  debug-http-requests: false

CF_Client:
  url: https://api.dev.cfdev.sh
  username: admin
  password: admin
  skip-ssl-validation: true
  HTTP_PROXY:
  HTTPS_PROXY:

Broker_API:
  port: 5000
  username: admin
  password: admin

actuator:
  enabled: false
  appUrl: http://localhost:5000
  endpoint: ""
  sprintBootAdminUrl: http://localhost:8080/instances
  username: ""
  password: ""